version: '2'

services:
    sel-hub:
        build:
            context: .
            dockerfile: DockerfileSel-Hub
        ports:
            - "4444:4444"  
        tty: true
    sel-node-1:
        build:
            context: .
            dockerfile: DockerfileSel-Node
        links:
        - sel-hub:hub
        tty: true
    sel-node-2:
        build:
            context: .
            dockerfile: DockerfileSel-Node
        links:
        - sel-hub:hub
        tty: true
    sel-node-3:
        build:
            context: .
            dockerfile: DockerfileSel-Node
        links:
        - sel-hub:hub
        tty: true
    sel-node-4:
        build:
            context: .
            dockerfile: DockerfileSel-Node
        links:
        - sel-hub:hub
        tty: true
