version: '2'

services:
    sel-host:
        build:
            context: .
            dockerfile: DockerfileSel-Host
        ports:
            - "4444:4444"  
        tty: true
        volumes:
        - ./Shared:/tmp/Shared
    sel-node-1:
        build:
            context: .
            dockerfile: DockerfileSel-Node
        links:
        - selhost
        tty: true
 #   sel-node-2:
 #       build:
 #           context: .
 #           dockerfile: DockerfileSel-Node
 #       links:
 #       - selhost
 #       tty: true
 #   sel-node-3:
 #       build:
 #           context: .
 #           dockerfile: DockerfileSel-Node
 #       links:
 #       - selhost
 #       tty: true
 #   sel-node-4:
 #       build:
 #           context: .
 #           dockerfile: DockerfileSel-Node
 #       links:
 #       - selhost
 #       tty: true
