version: '2'

services:
    selhost:
        build:
            context: .
            dockerfile: DockerfileSel-Host
          ports:
            - "4444:4444"  
        tty: true
    selnode:
        build:
            context: .
            dockerfile: DockerfileSel-Node
        links:
        - selhost
        tty: true
